version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    container_name: producer
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_MQ_HOST_ADDRESS=rabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USERNAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - PUBLISH_DELAY=5
    volumes:
      - logs:/logs
  
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: consumer
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_MQ_HOST_ADDRESS=rabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USERNAME=guest
      - RABBIT_MQ_PASSWORD=guest
    volumes:
      - logs:/logs

volumes:
  logs: